using Test
using Plots
using BioToolkit

@testset "Root entrypoint" begin
	@test isdefined(BioToolkit, :gc_content)
	@test gc_content("ATGC") == 0.5
	@test reverse_complement("ATGC") == "GCAT"
	@test DNASeq("ATGC") == BioToolkit.DNASeq("ATGC")
	@test GenomicInterval("chr1", 1, 2) isa GenomicInterval
	@test isdefined(BioToolkit, :find_variable_features)
	@test isdefined(BioToolkit, :calculate_rna_velocity)
	@test isdefined(BioToolkit, :calculate_dynamical_rna_velocity)
	@test isdefined(BioToolkit, :read_h5ad)
	@test isdefined(BioToolkit, :write_h5ad)
	@test isdefined(BioToolkit, :CellTypeAnnotationResult)
	@test isdefined(BioToolkit, :annotate_cell_types)
	@test isdefined(BioToolkit, :AmbientRNARemovalResult)
	@test isdefined(BioToolkit, :remove_ambient_rna)
	@test isdefined(BioToolkit, :SingleCellViewer)
	@test isdefined(BioToolkit, :interactive_singlecell_viewer)
	@test isdefined(BioToolkit, :lasso_select_cells)
	@test isdefined(BioToolkit, :recluster_singlecell_viewer!)
	@test isdefined(BioToolkit, :cell_hover_text)
	@test isdefined(BioToolkit, :top_expressed_genes)
	@test isdefined(BioToolkit, :plot_trajectory)
	@test isdefined(BioToolkit, :plot_rna_velocity)
	@test isdefined(BioToolkit, :plot_rna_velocity_quiver)
	@test isdefined(BioToolkit, :plot_communication_network)
	@test isdefined(BioToolkit, :plot_communication_pathways)
	@test isdefined(BioToolkit, :plot_ligand_receptor_report)
	@test isdefined(BioToolkit, :calculate_pseudotime)
	@test isdefined(BioToolkit, :find_neighbors)
	@test isdefined(BioToolkit, :find_spatial_neighbors)
	@test isdefined(BioToolkit, :find_clusters)
	@test isdefined(BioToolkit, :find_markers)
	@test isdefined(BioToolkit, :find_cell_communication)
	@test isdefined(BioToolkit, :communication_pathway_summary)
	@test isdefined(BioToolkit, :rank_ligand_receptor_report)
	@test isdefined(BioToolkit, :attach_spatial_coords!)
	@test isdefined(BioToolkit, :moran_i_test)
	@test isdefined(BioToolkit, :find_spatially_variable_genes)
	@test isdefined(BioToolkit, :weighted_nearest_neighbors)
	@test isdefined(BioToolkit, :predict_perturbation)
	@test isdefined(BioToolkit, :save_singlecell_experiment)
	@test isdefined(BioToolkit, :load_singlecell_experiment)
	@test isdefined(BioToolkit, :save_singlecell_archive)
	@test isdefined(BioToolkit, :load_singlecell_archive)
	@test isdefined(BioToolkit, :archive_to_singlecell_experiment)
	@test isdefined(BioToolkit, :browse_singlecell_archive)
	@test isdefined(BioToolkit, :archive_layer)
	@test isdefined(BioToolkit, :archive_embedding)
	@test isdefined(BioToolkit, :gpu_singlecell_experiment)
	@test isdefined(BioToolkit, :SingleCellArchive)
	@test isdefined(BioToolkit, :SingleCellArchiveBrowser)
	@test isdefined(BioToolkit, :SpatialMoranResult)
	@test isdefined(BioToolkit, :DynamicalRNAVelocityResult)
	@test isdefined(BioToolkit, :WNNResult)
	@test isdefined(BioToolkit, :PerturbationPredictionResult)
	@test isdefined(BioToolkit, :CommunicationPathwaySummary)
	@test isdefined(BioToolkit, :LigandReceptorReport)
	if Base.find_package("Makie") !== nothing
		@eval using Makie
		viewer_test_experiment = BioToolkit.SingleCellExperiment([10 0 1; 0 5 2; 1 2 8], ["g1", "g2", "g3"], ["c1", "c2", "c3"])
		viewer_test = BioToolkit.interactive_singlecell_viewer(viewer_test_experiment; embedding=Float64[0.0 0.0; 1.0 0.0; 0.0 1.0], labels=[1, 1, 2], k=2)
		extension = Base.get_extension(BioToolkit, :BioToolkitMakieExt)
		@test extension !== nothing
		figure = getfield(extension, Symbol("_viewer_figure"))(viewer_test)
		@test figure isa Makie.Figure
	end
	@test isdefined(BioToolkit, :window_coverage)
	@test isdefined(BioToolkit, :write_fastq)
	@test isdefined(BioToolkit, :SeqRecordLite)
	@test isdefined(BioToolkit, :pairwise_align)
	@test isdefined(BioToolkit, :motif_counts)
	@test isdefined(BioToolkit, :parse_gff_record)
	@test isdefined(BioToolkit, :annotate_genbank_record)
	@test isdefined(BioToolkit, :read_genbank)
	@test isdefined(BioToolkit, :Restriction)
	@test isdefined(BioToolkit, :Entrez)
	@test isdefined(BioToolkit, :Medline)
	@test isdefined(BioToolkit, :Compass)
	@test isdefined(BioToolkit, :Proteomics)
	@test isdefined(BioToolkit, :Metabolomics)
	@test isdefined(BioToolkit, :SystemsBio)
	@test isdefined(BioToolkit, :GWAS)
	@test isdefined(BioToolkit, :gwas_linear_scan)
	@test isdefined(BioToolkit, :manhattan_plot)
	@test isdefined(BioToolkit, :KEGG)
	@test isdefined(BioToolkit, :Pathway)
	@test isdefined(BioToolkit, :SCOP)
	@test isdefined(BioToolkit, :CATH)
end
