# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  # 1. GitHub Actions 
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # 2. Root project (Main Project.toml)
  - package-ecosystem: "julia"
    directory: "/"
    schedule:
      interval: "weekly"

  # 3. Docs (docs/Project.toml)
  - package-ecosystem: "julia"
    directory: "/docs"
    schedule:
      interval: "weekly"

  # 4. Test (test/Project.toml)
  - package-ecosystem: "julia"
    directory: "/test"
    schedule:
      interval: "weekly"